import test from 'node:test';import assert from 'node:assert/strict';
import evacuation from '../api/evacuation.js';import shelters from '../api/shelters.js';import utilities from '../api/utilities.js';import compatibility from '../api/arakawa.js';
const original=globalThis.fetch;
const evac=JSON.stringify({Update_At:'2026/09/21 16:20',Hinan_Anzenkakuho:{area:{features:[]}},Hinan_Shiji:{area:{features:[]}},Hinan_Zyunbi:{area:{features:[]}}});
const transport='<h3>JR 東日本</h3><p>現在、情報はありません。</p><h3>東京メトロ</h3><p>現在、情報はありません。</p><h3>京成電鉄</h3><p>現在、情報はありません。</p><h3>東京都交通局</h3><p>ウェブサイトにてご確認ください</p><h2>電気、ガス、水道、下水道</h2><h3>電気</h3><p>現在、情報はありません。</p>';
function mock(path){globalThis.fetch=async u=>{if(String(u).includes(path))return new Response('upstream unavailable',{status:503});return new Response(String(u).includes('get_json.php')?evac:String(u).includes('koukyou')?transport:'<table><tr><td>ひぐらし小学校</td><td>閉鎖中</td></tr></table>',{status:200})}}
async function invoke(handler){const r={statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v},end(s){this.body=JSON.parse(s)}};await handler({method:'GET'},r);return r}
test('shelter upstream failure does not hide evacuation or utilities',async()=>{mock('hinanjyo-ichiran');try{const e=await invoke(evacuation),u=await invoke(utilities),s=await invoke(shelters);assert.equal(e.statusCode,200);assert.equal(e.body.state,'none');assert.equal(u.statusCode,200);assert.equal(u.body.utilities.find(x=>x.id==='jr').state,'none');assert.equal(s.statusCode,502);const c=await invoke(compatibility);assert.equal(c.body.evacuation.state,'none');assert.equal(c.body.shelters.state,'error');assert.equal(c.body.utilities.state,'ok')}finally{globalThis.fetch=original}});
test('evacuation upstream failure is not converted to no announcement',async()=>{mock('get_json.php');try{const e=await invoke(evacuation);assert.equal(e.statusCode,502);assert.equal(e.body.state,'error');assert.match(e.headers['Cache-Control'],/no-store/);const c=await invoke(compatibility);assert.equal(c.body.evacuation.state,'error');assert.equal(c.body.utilities.state,'ok')}finally{globalThis.fetch=original}});
